#!/bin/sh /etc/rc.common
USE_PROCD=1
START=95
STOP=01
start_service() {
    procd_open_instance
    procd_set_param limits core="unlimited"
    procd_set_param command /usr/local/bin/lokinet /root/.lokinet/lokinet.ini
#    procd_set_param stdout 1 #stdout to log
#    procd_set_param stderr 1 #stderr to log
#    procd_set_param pidfile /var/run/lokinet.pid
    procd_set_param respawn \
	${respawn_threshold:-3600} \
	${respawn_timeout:-5} ${respawn_retry:-5}
    procd_close_instance
}

